### ISSUE TITLE
Make Windows Compatability Fix a DS Must-use plugin

### ISSUE THREAD

**Issue by davejesch** [ServerPress/Windows-Compatibility-Fix#1]
@Steveorevo commented on [Tue Mar 21 2017](https://github.com/ServerPress/ds/issues/98)

Plugins that use EDD fail on Windows; our WPSiteSync plugin fixes this. We should make this functionality into a Windows Design Time plugin. 

---

@jennifercloake commented on [Wed Mar 22 2017](https://github.com/ServerPress/ds/issues/98#issuecomment-288459052)

@GreggFranklin Assigning this to you for testing.  Once we are done with this, please assign it back to me.   We will shelf it, along with the documentation.  Can decide to release with 3.9 or 4.0 when Steve's done with Apache stuff.   

---

@davejesch commented on [Wed Mar 29 2017](https://github.com/ServerPress/ds/issues/98#issuecomment-290151723)

"Windows Compatibility Fix" public repo
checked in to https://github.com/ServerPress/Windows-Compatibility-Fix

---

@Steveorevo commented on [Mon Aug 27 2018](https://github.com/ServerPress/ds/issues/98#issuecomment-416285358)

Slated for must-use plugin in:
https://github.com/ServerPress/ds/issues/165

**Comment by Steveorevo** [comment]
Related to https://github.com/ServerPress/ds/issues/165

**Comment by davejesch** [comment]
implemented

**Comment by GreggFranklin** [comment]
Enhancement has been addded
